// flow-typed signature: 96d7fe482a342671bed8e3210713bb22
// flow-typed version: <<STUB>>/draft-js_vgit://github.com/facebook/draft-js.git#0.11.0-alpha/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'draft-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'draft-js' {
  declare module.exports: any;
}
